[server]
    host = '127.0.0.1'
    port = '8080'
    debug = 'true'

[database]
    host = 'localhost'
    port = 6432
    user = 'local_docker_hub'
    password = 'local_docker_hub'
    database = 'local_docker_hub'
    min_size = 4
    max_size = 12
    max_queries = 50000
    max_inactive_connection_lifetime = 300
